from segmentation import SimilarityIndex
from surface import IcosahedronResampler, QuadEdgeMeshClampScalars, BRAINSApplySurfaceLabels, BRAINSSurfaceGeneration, LabelMaps, QuadEdgeMeshHistogramMatching, ResampleQuadEdgeMesh, QuadEdgeMeshPiecewiseRescale, AssignArray, SurfaceColor, BRAINSMeasureSurface, SurfaceLabelCleanUp, MultiResolutionRegistration, BRAINSAssignSurfaceFeatures, ProbabilityLabels, RemoveTinyLabels, AverageScalarsByResampling, WarpQuadEdgeMesh, RearrangeSurfaceLabels, BRAINSSurfaceFlattening, SmoothingMeshScalars, QuadEdgeMeshSimilarity, CombineLabels
from classify import BRAINSPosteriorToContinuousClass
from utilities import HistogramMatchingFilter
