# use containers
sudo: false

os:
  - linux
#  - osx

language: cpp

cache: ccache

compiler:
#  - clang
  - gcc

#addons:
#  apt:
#    sources:
#      - george-edison55-precise-backports
#    packages:
#      - cmake
#      - cmake-data

before_install:
  - TOOLS_DIR=$(pwd)
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then CMAKE_URL="http://www.cmake.org/files/v3.10/cmake-3.10.2-Linux-x86_64.tar.gz"; fi
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then mkdir -p cmake && travis_retry wget --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake ; fi
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then export PATH=${TOOLS_DIR}/cmake/bin:${PATH} ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then echo "need cmake 3.9.5"; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update && brew install ccache cmake; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export PATH="/usr/local/opt/ccache/libexec:/usr/local/opt/cmake/bin:$PATH"; fi

script:
  # Minimize build time for testing
  - ${TOOLS_DIR}/cmake/bin/cmake --version
  - ls ${TRAVIS_BUILD_DIR}
  - mkdir -p ${TRAVIS_BUILD_DIR}/build
  - cd ${TRAVIS_BUILD_DIR}/build
  - pwd
  - ${TOOLS_DIR}/cmake/bin/cmake      -DUSE_ANTS=BOOL=OFF      -DUSE_BRAINSABC:BOOL=OFF      -DUSE_BRAINSDWICleanup:BOOL=OFF      -DUSE_BRAINSInitializedControlPoints:BOOL=OFF      -DUSE_BRAINSLabelStats:BOOL=OFF      -DUSE_BRAINSLandmarkInitializer:BOOL=OFF      -DUSE_BRAINSROIAuto:BOOL=OFF      -DUSE_BRAINSRefacer:BOOL=OFF      -DUSE_BRAINSResample:BOOL=OFF      -DUSE_BRAINSSnapShotWriter:BOOL=OFF      -DUSE_BRAINSStripRotation:BOOL=OFF      -DUSE_BRAINSTransformConvert:BOOL=OFF      -DUSE_ConvertBetweenFileFormats:BOOL=OFF      -DUSE_ImageCalculator:BOOL=OFF      -DUSE_ReferenceAtlas:BOOL=OFF      ${TRAVIS_BUILD_DIR}    && make -j 2    && make -C BRAINSTools-build/ test

notifications:
  email:
    recipients:
      - hans-johnson@uiowa.edu
