dist: xenial
language: cpp
# use containers
sudo: false

os:
  - linux
#  - osx

# http://www.brianlheim.com/2017/08/20/supercollider-travisci.html
# use ccache to speed up build times. on osx,
# we install it during the the before_install step
# with xcode, this requires an additional flag passed during the configuration phase.
# see README_MACOS.md for details.
cache:
  - ccache

compiler:
  - clang
  - gcc

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
      - valgrind
  homebrew:
    packages:
      - cmake
      - ccache
      - sed

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export PATH="/usr/local/opt/ccache/libexec:$PATH"; fi

script: ./.travis_build_script.sh

notifications:
  email:
    recipients:
      - hans-johnson@uiowa.edu
