# Build matrix / environment variables are explained on:
# http://about.travis-ci.org/docs/user/build-configuration/
# This file can be validated on:
# http://lint.travis-ci.org/
# See also
# http://stackoverflow.com/questions/22111549/travis-ci-with-clang-3-4-and-c11/30925448#30925448
# to allow C++11, though we are not yet building with -std=c++11
language: cpp
sudo: false

os:
  - linux
#  - osx

# http://www.brianlheim.com/2017/08/20/supercollider-travisci.html
# use ccache to speed up build times. on osx,
# we install it during the the before_install step
# with xcode, this requires an additional flag passed during the configuration phase.
# see README_MACOS.md for details.
cache:
  - ccache

compiler:
#  - clang
  - gcc

git:
  depth: false # Need the full depth of the repo for version history

#cache: ccache  <-- todo investigate
#use containers  <-- todo investigate

addons:
#  homebrew:
#    packages:
#    - ninja
#    - cmake
#    update: false # do not update homebrew by default
  #apt:
    #sources:
    #- llvm-toolchain-precise-3.5
    #packages:
    #- gcc-4.9
    #- g++-4.9
    #- clang-3.5
    #- valgrind
matrix:
#  allow_failures:
#    - os: osx
  include:
#    - name: Mac clang static release testing
#      os: osx
#      osx_image: xcode9.4
#      compiler: clang
#      script: ./.travis_build_script.sh
#    - name: xenial clang static release testing
#      os: linux
#      dist: xenial
#      compiler: clang
#      script: ./.travis_build_script.sh
    - name: xenial gcc cmake coverage
      os: linux
      dist: xenial
      compiler: gcc
      script: ./.travis_build_script.sh
#   Valgrind has too many false positives from the python wrapping.  Need a good suppression file
#    - name: xenial gcc cmake coverage
#      os: linux
#      dist: xenial
#      compiler: gcc
#      script: ./.travis_build_script.sh
notifications:
  email:
    recipients:
      - hans-johnson@uiowa.edu
