dist: xenial
language: cpp
# use containers
sudo: false

os:
  - linux
  - osx

cache: ccache

compiler:
  - clang
  - gcc

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
      - valgrind
  homebrew:
    packages:
      - cmake
      - ccache
      - sed

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export PATH="/usr/local/opt/ccache/libexec:$PATH"; fi

script: ./.travis_build_script.sh

notifications:
  email:
    recipients:
      - hans-johnson@uiowa.edu
