dist: xenial
language: cpp
# use containers
sudo: false

os:
  - linux
  - osx


cache: ccache

compiler:
  - clang
  - gcc

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
      - valgrind
  homebrew:
    packages: cmake
    package:  sed

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then echo "need cmake 3.2"; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update && brew install ccache; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export PATH="/usr/local/opt/ccache/libexec:$PATH"; fi
  - mkdir bt-bld
  - cd bt-bld

script:
  # Minimize build time for testing
  - cmake \
    -DCMAKE_CXX_STANDARD:STRING=11 \
     -DUSE_ANTS=BOOL=OFF \
     -DUSE_BRAINSABC:BOOL=OFF \
     -DUSE_BRAINSDWICleanup:BOOL=OFF \
     -DUSE_BRAINSInitializedControlPoints:BOOL=OFF \
     -DUSE_BRAINSLabelStats:BOOL=OFF \
     -DUSE_BRAINSLandmarkInitializer:BOOL=OFF \
     -DUSE_BRAINSROIAuto:BOOL=OFF \
     -DUSE_BRAINSRefacer:BOOL=OFF \
     -DUSE_BRAINSResample:BOOL=OFF \
     -DUSE_BRAINSSnapShotWriter:BOOL=OFF \
     -DUSE_BRAINSStripRotation:BOOL=OFF \
     -DUSE_BRAINSTransformConvert:BOOL=OFF \
     -DUSE_ConvertBetweenFileFormats:BOOL=OFF \
     -DUSE_ImageCalculator:BOOL=OFF \
     -DUSE_ReferenceAtlas:BOOL=OFF \
    ./.. \
    && make -j 2 && cd BRAINSTools-build/ && make test

notifications:
  email:
    recipients:
      - hans-johnson@uiowa.edu
