# Package BRAINSTools
#https://cmake.org/Wiki/CMake:Component_Install_With_CPack

 set(CPACK_PACKAGE_NAME "BRAINSTools")
 set(CPACK_PACKAGE_VENDOR "SINAPSE LAB U Iowa")
 set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "BRAINSTools")
 set(CPACK_PACKAGE_VERSION_MAJOR "${${PROJECT_NAME}_VERSION_MAJOR}")
 set(CPACK_PACKAGE_VERSION_MINOR "${${PROJECT_NAME}_VERSION_MINOR}")
 set(CPACK_PACKAGE_VERSION_PATCH "${${PROJECT_NAME}_VERSION_PATCH}")
 set(CPACK_PACKAGE_VERSION "${CPACK_PACKAGE_VERSION_MAJOR}.${CPACK_PACKAGE_VERSION_MINOR}.${CPACK_PACKAGE_VERSION_PATCH}")
 set(CPACK_PACKAGE_INSTALL_DIRECTORY "CPack Component Example")
 # This must always be last!
 include(CPack)
