# -*- coding: utf8 -*- 
"""Autogenerated file - DO NOT EDIT
If you spot a bug, please report it on the mailing list and/or change the generator."""

from nipype.interfaces.base import CommandLine, CommandLineInputSpec, SEMLikeCommandLine, TraitedSpec, File, Directory, traits, isdefined, InputMultiPath, OutputMultiPath
import os


class CompareSurfacesInputSpec(CommandLineInputSpec):
    inputSurfaceFile = File(desc="The input surface to compare", exists=True, argstr="--inputSurfaceFile %s")
    refSurfaceFile = File(desc="The reference surface to compare with", exists=True, argstr="--refSurfaceFile %s")
    vertexLocation = traits.Bool(desc="Compare vertex locations", argstr="--vertexLocation ")
    scalarArray = traits.Bool(desc="Compare all of the scalar arrays", argstr="--scalarArray ")
    cellData = traits.Bool(desc="Compare all of the cell data", argstr="--cellData ")
    tolerance = traits.Float(desc="The tolerance within which the surfaces must be similar", argstr="--tolerance %f")


class CompareSurfacesOutputSpec(TraitedSpec):
    pass


class CompareSurfaces(SEMLikeCommandLine):
    """title: 
    Surface Comparision
  

category: 
    SurfaceComparision
  

description: 
    This program compares input surface with reference surface. All of the vertex locations are compared from input surface with reference surface and also the scalar array names and scalar values of points or cells.
  

version: 0.1.0.$Revision: 1 $(alpha)

contributor: Wen Li and Vincent A. Magnotta

acknowledgements: Funding for this work was provided by NIH/NINDS award NS050568

"""

    input_spec = CompareSurfacesInputSpec
    output_spec = CompareSurfacesOutputSpec
    _cmd = " CompareSurfaces "
    _outputs_filenames = {}
