title: BRAINSTools
description: A suite of tools for medical image processing focused on brain analysis
google_analytics: 
show_downloads: true
theme: jekyll-theme-modernist

gems:
  - jekyll-mentions
