trigger:
  branches:
    include:
    - master
    - release*
jobs:
- job: Linux
  timeoutInMinutes: 0
  cancelTimeoutInMinutes: 300
  pool:
    vmImage: ubuntu-16.04
  steps:
    - script: |
        set -x

        git clone -b dashboard --single-branch https://github.com/BRAINSia/BRAINSTools.git BRAINSTools-dashboard

        sudo pip3 install ninja

        c++ --version
        cmake --version

        export BUILD_EXAMPLES=OFF
        export CTEST_BUILD_CONFIGURATION=MinSizeRel

        ctest -S BRAINSTools-dashboard/azure_dashboard.cmake -VV -j 4
      displayName: Build and Test
      workingDirectory: $(Agent.BuildDirectory)
