## \author Hans J. Johnson
## This file contains the code necessary to build the python module
## nodes for SEM compliant tools
##

## NOTES ON HOW TO RUN THIS.
# export PATH=/ipldev/scratch/johnsonhj/src/BRAINSStandAlone-Darwin-clang/lib:${PATH}
# export PYTHONPATH=/ipldev/sharedopt/20120201/Darwin_i386/PYTHON_MODULES/lib/python2.7/site-packages
# export PYTHONPATH=/ipldev/sharedopt/20120201/Darwin_i386/PYTHON_MODULES
# nipype/interfaces/slicer/generate_classes.py
#cd ~/src/BRAINSStandAlone/AutoWorkup/SEMTools/; rm -rf ~/src/BRAINSStandAlone/AutoWorkup/SEMTools/* ; python ../BRAINSTools/local_generate_classes.py

from nipype.interfaces.slicer.generate_classes import generate_all_classes

modules_list = [
  'AssignArray',
  'AverageBrainGenerator',
  'AverageScalarsByResampling',
  'BRAINSABC',
  'BRAINSAlignMSP',
  'BRAINSApplySurfaceLabels',
  'BRAINSAssignSurfaceFeatures',
  'BRAINSClipInferior',
  'BRAINSConstellationDetector',
  'BRAINSConstellationModeler',
  'BRAINSContinuousClass',
  'BRAINSCut',
  'BRAINSDemonWarp',
  'BRAINSEyeDetector',
  'BRAINSFit',
  'BRAINSFitEZ',
  'BRAINSFitEZ',
  'BRAINSInitializedControlPoints',
  'BRAINSLandmarkInitializer',
  'BRAINSLinearModelerEPCA',
  'BRAINSLmkTransform',
  'BRAINSMeasureSurface',
  'BRAINSMultiModeSegment',
  'BRAINSMush',
  'BRAINSPosteriorToContinuousClass',
  'BRAINSROIAuto',
  'BRAINSResample',
  'BRAINSResize',
  'BRAINSSnapShotWriter',
  'BRAINSSurfaceFlattening',
  'BRAINSSurfaceGeneration',
  'BRAINSTransformConvert',
  'BRAINSTransformFromFiducials',
  'BRAINSTrimForegroundInDirection',
  'BinaryMaskEditorBasedOnLandmarks',
  'CannyEdge',
  'CannySegmentationLevelSetImageFilter',
  'CleanUpOverlapLabels',
  'CombineLabels',
  'CompareSurfaces',
  'CreateMask',
  'DilateImage',
  'DilateMask',
  'DistanceMaps',
  'ESLR',
  'ErodeImage',
  'FlippedDifference',
  'GenerateBrainClippedImage',
  'GenerateCsfClippedFromClassifiedImage',
  'GenerateLabelMapFromProbabilityMap',
  'GenerateSummedGradientImage',
  'GenerateTestImage',
  'GradientAnisotropicDiffusionImageFilter',
  'HammerAttributeCreator',
  'HistogramMatchingFilter',
  'IcosahedronResampler',
  'ImageRegionPlotter',
  'JointHistogram',
  'LabelMaps',
  'MultiResolutionRegistration',
  'NeighborhoodMean',
  'NeighborhoodMedian',
  'NoiseGenerator',
  'ProbabilityLabels',
  'QuadEdgeMeshClampScalars',
  'QuadEdgeMeshHistogramMatching',
  'QuadEdgeMeshPiecewiseRescale',
  'QuadEdgeMeshSimilarity',
  'RearrangeSurfaceLabels',
  'RemoveTinyLabels',
  'ResampleQuadEdgeMesh',
  'STAPLEAnalysis',
  'ShuffleVectorsModule',
  'SimilarityIndex',
  'SurfaceColor',
  'SurfaceLabelCleanUp',
  'TextureFromNoiseImageFilter',
  'TextureMeasureFilter',
  'VBRAINSDemonWarp',
  'WarpQuadEdgeMesh',
  'compareTractInclusion',
  'extractNrrdVectorIndex',
  'fcsv_to_hdf5',
  'gtractAnisotropyMap',
  'gtractAverageBvalues',
  'gtractClipAnisotropy',
  'gtractCoRegAnatomy',
  'gtractConcatDwi',
  'gtractCopyImageOrientation',
  'gtractCoregBvalues',
  'gtractCostFastMarching',
  'gtractCreateGuideFiber',
  'gtractFastMarchingTracking',
  'gtractFiberTracking',
  'gtractImageConformity',
  'gtractInvertBSplineTransform',
  'gtractInvertDisplacementField',
  'gtractInvertRigidTransform',
  'gtractResampleAnisotropy',
  'gtractResampleB0',
  'gtractResampleCodeImage',
  'gtractResampleDWIInPlace',
  'gtractResampleFibers',
  'gtractTensor',
  'gtractTransformToDisplacementField',
  'iccdefRegistration_New',
  'insertMidACPCpoint',
  'landmarksConstellationAligner',
  'landmarksConstellationWeights',
  'SmoothingMeshScalars'
  ]

launcher=['']
generate_all_classes(modules_list=modules_list, launcher=[])
