# -*- coding: utf8 -*-
"""Autogenerated file - DO NOT EDIT
If you spot a bug, please report it on the mailing list and/or change the generator."""

from nipype.interfaces.base import CommandLine, CommandLineInputSpec, SEMLikeCommandLine, TraitedSpec, File, Directory, traits, isdefined, InputMultiPath, OutputMultiPath
import os


class DTIPrepInputSpec(CommandLineInputSpec):
    DWINrrdFile = File(desc="DWI file name to convert dicom image series into or to be checked (nrrd/nhdr)", exists=True, argstr="--DWINrrdFile %s")
    xmlProtocol = File(desc="protocol xml file containing all the parameters", exists=True, argstr="--xmlProtocol %s")
    resultNotesFile = File(desc="result notes", exists=True, argstr="--resultNotesFile %s")
    outputFolder = traits.Either(traits.Bool, Directory(), hash_files=False, desc="DTIPrep creates the output folder via using both absolute path (starts with \'/\') and relative path. The realtive path does not start with \'/\'. If the relative path ends with \'/\' means that the output folder will be created in current location, otherwise the output folder will be created in the same folder as dwi image.", argstr="--outputFolder %s")
    default = traits.Bool(desc="create default protocol xml file", argstr="--default ")
    check = traits.Bool(desc="check by protocol xml file. Default operation", argstr="--check ")
    numberOfThreads = traits.Int(desc="Sets the number of threads used by multithreaded ITK filters", argstr="--numberOfThreads %d")


class DTIPrepOutputSpec(TraitedSpec):
    outputFolder = Directory(desc="DTIPrep creates the output folder via using both absolute path (starts with \'/\') and relative path. The realtive path does not start with \'/\'. If the relative path ends with \'/\' means that the output folder will be created in current location, otherwise the output folder will be created in the same folder as dwi image.", exists=True)


class DTIPrep(SEMLikeCommandLine):
    """title: DTIPrep

category: Diffusion

description: 
    The DWI/DTI Quality Control Processes from dicom data to qualified dwi image.
  

version: 1.2.4

contributor: Mahshid Farzinfar (1), Zhexing Liu (1), Martin Styner(1),Hans Johnson(2,3,4), Joy Matsui(2), Kent Williams(2); (1=Department of Psychiatry, University of North Carolina at Chapel Hill, 2=University of Iowa Department of Psychiatry, 3=University of Iowa Department of Biomedical Engineering, 4=University of Iowa Department of Electrical and Computer Engineering)


acknowledgements:  This work is part of the National Alliance for Medical Image Computing NAMIC, the IBIS (Infant Brain Imaging Study) Network which is NIH funded Autism Center of Excellence (HDO55741) and additional support is provided by the following grants: NIH grants P50 MH 064065, MH070890, P30 HD03110, R01 MH091645, U54 EB005149-01 (NA-MIC) , R01 NS061965, as well as by the Track-HD project funded by the CHDI/High Q Foundation.


"""

    input_spec = DTIPrepInputSpec
    output_spec = DTIPrepOutputSpec
    _cmd = " DTIPrep "
    _outputs_filenames = {'outputFolder':'outputFolder'}
